### ISSUE TITLE
SECURITY ISSUE: next parameter can redirect to any phishing site you like.

### ISSUE THREAD

**Issue by aphillipo** [lingthio/Flask-User#119]
Hi Guys,

Working at a security firm right now and they tell me the next URL can be crafted in various ways to point to a phishing site after you login.

So with flask_user I can make a link to the login page like:

http://yourealsite.com/login/?next=http://my-fake-malicous-site.com/login/

If I show a phishing site with the same login page and error I can harvest peoples logins.

Solution: the next parameter should be filtered such that no domain/http/protocol is included.

**Comment by lingthio** [comment]
Thank you for reporting this issue!

**Comment by Laogeodritt** [comment]
Hi there, came to report this same issue—since it's already here, I have some further thoughts on a general-purpose solution to this problem.

> Solution: the next parameter should be filtered such that no domain/http/protocol is included.

I believe Flask's `url_for` (which is used to populate `next` in a normal scenario) generates a URL with protocol/hostname/port equal to the current request's (or there is at least some configuration where that's true). You'd have to `urllib.parse` it, validate it, and strip these parts before passing to `redirect()`, which seems inelegant.

Another issue might be that, in some cases, you intentionally redirect to a known different domain (e.g. Flask app that works over several subdomain, or you make use of a remote login API like OAuth to access your app's accounts).

While looking at potential solutions to this issue that can work with safe absolute URLs, I came across this snippet that seems reasonable (written for py2—in py3, `urlparse` module is `urllib.parse`): http://flask.pocoo.org/snippets/62/

It checks that the protocol is http or https, and that the hostname for the request and `next` redirect are the same (maybe it would be better to check the port too?). I personally wrapped `werkzeug.utils.redirect` in a custom method and call this instead of `redirect` when using potentially unsafe URLs:

    def safe_redirect(location, *args, **kwargs):
        response = unsafe_redirect(location, *args, **kwargs)
        if not response.headers.get('Location', None) or is_safe_url(response.headers.get('Location')):
            return response
        else:
            raise ValueError("Unsafe redirect blocked")

This seems pretty reasonable in general, but in some cases an app might need to use a different domain redirect (if the app handles subdomains with a common login, or is e.g. an OAuth login that redirects to a third-party site). Being able to specify a custom redirect filter might be useful in this case, for flask_user default views.

I might suggest as a solution for the flask_user views:

a) accept an `is_url_safe` callable in the UserManager constructor (with all the appropriate security warnings in documentation);
b) use a default `is_url_safe` implementation like above;
c) in flask_user, use a wrapper around `redirect()` to make sure that the `next` parameter is safe by checking `is_url_safe` (or by checking the Location header of the Response set by `redirect` if preferred, as it does do some conversion/normalisation—I haven't looked too deeply at this). (Maybe you can make this safe_redirect available in the API as `flask_user.safe_redirect` or something too, for any custom views users may write that use this `next` pattern.)

**Comment by lingthio** [comment]
@Laogeodritt or @LotosikRa : Care to prepare a pull request?

**Comment by LotosikRa** [comment]
@lingthio : not on this week.

**Comment by Laogeodritt** [comment]
@lingthio Not at the moment, but I would be glad to when I have the time—might be in a couple weeks. If no one else has gotten to it when my time frees up, I'll comment back and take it on.

**Comment by Laogeodritt** [comment]
@lingthio and others: Can we envision any situation that an app using Flask-User would intentionally want to redirect back to a different hostname? e.g. an app that spans multiple subdomains (does Flask-User support setting wildcard cookies for subdomains, or is this a moot example?), or OAuth/remote auth-style authentication methods? Not sure if similar scenarios are realistic - if they are, we can envision customising the "safe URL" filter at the UserManager constructor or similar.

@bbc2 - Are you intending to pullreq your changes soon? I was considering working on this but I'm not sure what your change's status/intent is - from the diff looks functional aside the exceptional situation I mentioned above.

**Comment by lingthio** [comment]
I'm thinking of tackling this in a few days. I'm proposing a customizable `sanatize_url(url)` function. 

The default implementation will simply strip off optional hostnames. The developer can provide a custom function to allow a set of permissible hostnames. This proposal allows for full customization with a safe default behaviour.

Comments?

**Comment by aphillipo** [comment]
The correct solution is what phoenix does; if you want to redirect externally to a different URL you must specify ```redirect(external="http://full_url.com/")``` otherwise all redirects should start with ```/``` and error if not: 

```
redirect("/my/new/path/") # works
redirect("http://full_url.com/phishing.php") # errors -> UnsafeRedirectException?
```

**Comment by lingthio** [comment]
Fixed and released in v0.6.11
Thank you for the contributors that requested and discussed this issue.

**Comment by Laogeodritt** [comment]
@aphillipo That seems very sensible and should probably be raised with werkzeug upstream (since `redirect ()`is provided by the werkzeug project, which is a Flask dependency). Unfortunately, since that does change the API, backwards compatibility would probably have to be maintained...

@lingthio To be clear, the developer would provide a custom `make_safe_url(url)`? I guess docs/recommendation-wise, they could return safe hostnames, and call the original `make_safe_url` for unsafe hostnames.

That seems like a good implementation.

I would also point out this article, linked on the flask.pocoo.org snippet from earlier, in case it affects the implementation; it discusses some vulnerabilities with maliciously crafted URLs that appear relative to various back-end URL parsing libraries but may be interpreted as absolute URL by browsers: https://homakov.blogspot.ca/2014/01/evolution-of-open-redirect-vulnerability.html

**Comment by Laogeodritt** [comment]
Oh! Well that was quick. Cheers!

**Comment by swergas** [comment]
@lingthio I read the snippet http://flask.pocoo.org/snippets/62/ mentioned by @Laogeodritt as well as the comments on the snippet page. Last comment from landakram refers to starting an URL by 6 slashes. I just tried this with latest flask_user version 0.6.21. The issue still occurs (with default `views.make_safe_url` function). For example: http://localhost:5000/user/sign-in?next=//////google.com redirects to google.com after login.

So we should propably re-open this issue.

**Comment by mvfpoa** [comment]
I crawled for a solution, but it seems there is no congruence about it. Just wanted to share I just did a snipet for me that seems to be totally safe if you only want to work with local redirects:

```
import flask
next = flask.request.args.get('next')
for r in flask.current_app.url_map._rules:
  if r.rule == next:
    return flask.redirect(next)
return flask.redirect('.index')
```
This guarantee you can only redirect to registered views.

P.S. I am using flask-login

**Comment by mh453Uol** [comment]
> I crawled for a solution, but it seems there is no congruence about it. Just wanted to share I just did a snipet for me that seems to be totally safe if you only want to work with local redirects:
> 
> ```
> import flask
> next = flask.request.args.get('next')
> for r in flask.current_app.url_map._rules:
>   if r.rule == next:
>     return flask.redirect(next)
> return flask.redirect('.index')
> ```
> 
> This guarantee you can only redirect to registered views.
> 
> P.S. I am using flask-login

This works well for url like /books, /people etc however could not get it working for url like /books/1 `@app.route(/book/<isbn>)`.

So a solution which lots of other website use such as stackoverflow is having a query string which has the full absolute path to the redirect - https://stackoverflow.com/users/login?ssrc=head&returnurl=https://stackoverflow.com/questions/41416411/flask-signing-in-and-signing-out

Then when redirecting see if the server host matches the redirect host so `stackoverflow.com==stackoverflow.com`

Snippet of code which compares the server host with the redirect host using Flask
```
from urllib.parse import urlparse

# Only redirect if the passed in absolute url matches the server host to protect against phising
def safe_redirect(absolute_redirect_url):
    server_host = request.host
    #  general structure of a URL: scheme://netloc/path;parameters?query#fragment
    redirect_host = urlparse(absolute_redirect_url).netloc
    
    return server_host == redirect_host
```
Hope this helps someone :)
