### ISSUE TITLE
role and confirm email required

### ISSUE THREAD

**Issue by LotosikRa** [lingthio/Flask-User#122]
Question:

How to make access to the view for users that are registered, confirmed email and have a current role?

I know about `@roles_required` and `@confirm_email_required` . But is it a specific order to define them or another solution?

**Comment by lingthio** [comment]
Hi @LotosikRa , I'm not quite sure what you're asking for. Can you elaborate please?

**Comment by LotosikRa** [comment]
Hi @lingthio , I have gone over source code and know I think that it doesn't matter. But, I'm not using decorators, but I'm using functions from `access.py` file, so I'm not sure about `required_role`. 

I'm talking about how to pace decorators:
```
@role_required()
@confirm_email_required
# or...
@confirm_email_required
@role_required()
```

**Comment by lingthio** [comment]
`@role_required()` is invalid. First, it needs an extra 's' behind 'role'. Second, it needs one or more role names

> @roles_required('some_role_name')

The order is only relevant if the user has NO roles and has NOT yet confirmed the email.

> @roles_required('some_role_name')
> @confirm_email_required

Will produce the `unauthorized_view` view.

> @confirm_email_required
> @roles_required('some_role_name')

Will produce the `unconfirmed_email_view` view.

Did that answer your question?

On another note: Would you mind emailing ling.thio AT gmail.com? I'd like to discuss the idea of using OOP to customize the UserManager class (instead of a settings file and a list of custom functions in the init() method). Thanks.

**Comment by LotosikRa** [comment]
@lingthio : Yes, the answer is full.

Second answer: yes, I have sent an email to you.
