### ISSUE TITLE
can't install pycrypto package

### ISSUE THREAD

**Issue by LotosikRa** [lingthio/Flask-User#124]
I can't install `pycrypto` package.

I described my problem [on this page](https://github.com/dlitz/pycrypto/issues/133#issuecomment-235196376).

But pycrypto's repository seems to be dead, and no one will ask on my question.

Can anyone help me?

**Comment by LotosikRa** [comment]
[Answer from Stack Overflow](http://stackoverflow.com/a/22077790/6233648)

**Comment by justinfay** [comment]
@LotosikRa this issue isn't related to flask-user, I think you need to open it with your distros or pycryptos maintainer. Can you close this issue.

**Comment by drdaeman** [comment]
Sorry to bother, but I think I'll bump this issue a bit.

How about replacing long-dead `pycrypto` with `pycryptodome` (drop-in fork) or, possibly, something modern like `cryptography` (maybe even use its `Fernet` instead of `AES`+`TimestampSigner`, although this is would be backwards-incompatible)?
