### ISSUE TITLE
SECURITY ISSUE: reset_password_token exposed in the user table.

### ISSUE THREAD

**Issue by 3noch** [lingthio/Flask-User#159]
The `reset_password_token` column stores a plaintext token that can be used to reset a password. If the DB is compromised this token can be trivially used to gain access to accounts.

**Comment by lingthio** [comment]
Hi @3noch ,

In the default behaviour, this token is generated by TokenManager.generate_token().
This token is both encrypted, and signed with a timestamp:

`return` self.signer.sign(self.encrypt_id(id)).decode()`

So it's secure and only valid for a few hours (configurable).
See https://github.com/lingthio/Flask-User/blob/v0.6/flask_user/tokens.py

**Comment by 3noch** [comment]
@lingthio The issue is that the same token which is used in reset URLs is also stored in the database. This means an attacker who can get a copy of the database can create valid password-reset URLs for other users and change their passwords.

**Comment by lingthio** [comment]
Although the reset_password_token is:

- user specific,
- only valid for two days, and
- encrypted and signed

@3noch does have a point that a hacker with access to the DB would be able to reset the passwords for users that have started (but not completed) a password reset in the past two days.

It turns out that the reset_password_token DB field was a remnant of a v0.1 implementation and the workaround is quite simple: Remove the reset_password_token from the User (or UserAuth) table. Flask-User v0.5 and up will work without this DB field.

I will update all the docs and example apps to reflect this increased security approach.

Thank you @3noch for taking the time to report this. It's the open-source concept with community members like you that make the internet a safer place.

Fixed in v0.5+ by removing the reset_password_token from the User (or UserAuth) table.

**Comment by 3noch** [comment]
@lingthio Thank you! I defer all credit to @bladams who discovered it in our code.
