### ISSUE TITLE
Doesn't comply with Pocoo guidelines for approved extensions

### ISSUE THREAD

**Issue by Xender** [lingthio/Flask-User#89]
Hi there.

This Issue is related to #76, but now it's about guidelines conformance and possible corner-cases, while the former was about the API usage (and initial request there has been fully implemented), so I think it's better to create a new one.

Flask extension development guidelines state that extension's `__init__` should set `self.app`, but `init_app` must not.
You can find it both [online](http://flask.pocoo.org/docs/0.10/extensiondev/#the-extension-code) and in [copy of guidelines in this repo](https://github.com/lingthio/Flask-User/blob/ed65b106/misc/approved_extension.txt#L20-L21).

So Flask guidelines basically states that extension object should be a clean factory, and if there is some state depending both on extension and app object, `init_app` should register some new object (`app.extensions['ext_name'] = state_obj`).

Approved extensions do it this way:
[Flask-SQLAlchemy](https://github.com/mitsuhiko/flask-sqlalchemy/blob/ac135c67/flask_sqlalchemy/__init__.py#L804)
[Flask-DebugToolbar](https://github.com/mgood/flask-debugtoolbar/blob/14cd912d/flask_debugtoolbar/__init__.py#L74-L84)
[Flask-Mail](https://github.com/mattupstate/flask-mail/blob/e195fca6/flask_mail.py#L581-L585)

I don't fully comprehend this design, yet guidelines state that it is the way to support multiple app instances running in the same process, which is important for scenarios like tests etc..
I also wasn't aware of this when creating #76.

How do you think - is refactoring required to comply with this guideline is feasible and important enough?

**Comment by neurosnap** [comment]
It'd be easier to understand this problem if there was some edge case that was getting hit and reproducible or even a PR with a fix.

So what's the solution?  It looks like all app configuration settings get pushed to a state object that stores all configuration settings and then app['extensions'] is created/key added with all those settings.  That's doesn't seem too difficult and I don't see any reason why this sort of change would break any apps currently.

I'm all for Flask guideline compliance, but we also don't want to be overzealous because we've seen sticking to Flask's guidelines bite us before mitsuhiko/flask#115

Best case scenario with a fix is that some potential edge-cases that haven't been determined yet will never come to fruition and essentially nothing will change.  Worst case scenario is we break backwards compat in unknown ways.

Pros:
* Flask extension compliance
* Fix unknown edge cases

Cons:
* Potentially break previous configurations in unknown ways

Result:
* Nothing will change for the end developer

**Comment by Xender** [comment]
I too have mixed feelings about that and I'm unable to come to a conclusion.

I think the main question should be whether @lingthio wants to try to have Flask-User approved.

I can make a PR, I just wanted to discuss it beforehand.

I've tried to find multiple app object scenarios - one could be creating a JSON API with custom error handlers - but I've found it only in [some example app](https://github.com/mattupstate/overholt/blob/e03209f7a059d165a9154355d090738af3159028/overholt/api/__init__.py#L19-L33).

As for breaking compat in unknown ways - hmm.
The only breakage scenario I can imagine would be application developer accessing `.app` member of `UserManager` instance object in environment with application factory, and this probably means developer's bad design (probably being unaware of how it should work).
Yet there may be other scenarios I cannot imagine.

If we have unknown edge cases to be fixed and potential unknown edge cases to be broken, I'd put those aside and think mainly about other arguments (compliance vs. work needed).

**Comment by lingthio** [comment]
@Xender : Thank you for noticing this issue. I will see if this change will break anything internally, and if not, I will make the change and post a warning on the docs. This may take a while since I am swamped right now.

**Comment by lingthio** [comment]
I fixed this in Flask v1.0.

**Comment by Sebi2020** [comment]
Thats's wrong. The extension still requires the user to hand over app,db and user class on class initializiation instead of making the optional until the user (or the class) calls init_app.

**Comment by Sebi2020** [comment]
> I fixed this in Flask v1.0.

Thats's not true. The extension still requires the user to hand over `app`,`db` and `user` class on class initializiation instead of making them optional until the user (or the class if an `app` instance was handed over) calls init_app.
